export const ADD_SHOPCART = 'ADD_SHOPCART';
export const REDUCE_SHOPCART = 'REDUCE_SHOPCART';
export const EMPTY_SHOPCART = 'EMPTY_SHOPCART';
export const SELECTTYPE_RATING = 'SELECTTYPE_RATING';
export const ONLYCONTENT_RATING = 'ONLYCONTENT_RATING';
